// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#ifndef RENDER_STYLE_PROPERTIES_INITIAL_INLINES_INCLUDE_TRAP
#error "Please do not include this file anywhere except from RenderStyleInlines.h."
#endif

#include <WebCore/RenderStylePropertiesInitialCustom.h>

namespace WebCore {

constexpr Style::TestEnumeration RenderStyleProperties::initialTestRenderStyleStorageOneLevelEnum()
{
    return Style::TestEnumeration::Foo;
}

constexpr Style::TestRaw RenderStyleProperties::initialTestRenderStyleStorageOneLevelRaw()
{
    return CSS::Keyword::Foo { };
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageOneLevelReference()
{
    using namespace CSS::Literals;
    return 0_css_number;
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageOneLevelValue()
{
    using namespace CSS::Literals;
    return 0_css_number;
}

constexpr Style::TestEnumeration RenderStyleProperties::initialTestRenderStyleStorageTwoLevelEnum()
{
    return Style::TestEnumeration::Foo;
}

constexpr Style::TestRaw RenderStyleProperties::initialTestRenderStyleStorageTwoLevelRaw()
{
    return CSS::Keyword::Foo { };
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageTwoLevelReference()
{
    using namespace CSS::Literals;
    return 0_css_number;
}

inline Style::Number<> RenderStyleProperties::initialTestRenderStyleStorageTwoLevelValue()
{
    using namespace CSS::Literals;
    return 0_css_number;
}

} // namespace WebCore

