// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#pragma once

#include <WebCore/RenderStyleBase.h>

namespace WebCore {

class RenderStyleProperties : public RenderStyleBase {
protected:
    RenderStyleProperties(RenderStyleProperties&&) = default;
    RenderStyleProperties& operator=(RenderStyleProperties&&) = default;

    RenderStyleProperties(CreateDefaultStyleTag tag) : RenderStyleBase { tag } { }
    RenderStyleProperties(const RenderStyleProperties& other, CloneTag tag) : RenderStyleBase { other, tag } { }

    RenderStyleProperties(RenderStyleProperties& a, RenderStyleProperties&& b) : RenderStyleBase { a, WTFMove(b) } { }

public:
    // CSSPropertyID::CSSPropertyTestRenderStyleStorageOneLevelEnum
    inline Style::TestEnumeration testRenderStyleStorageOneLevelEnum() const;
    inline void setTestRenderStyleStorageOneLevelEnum(Style::TestEnumeration);

    // CSSPropertyID::CSSPropertyTestRenderStyleStorageOneLevelRaw
    inline Style::TestRaw testRenderStyleStorageOneLevelRaw() const;
    inline void setTestRenderStyleStorageOneLevelRaw(Style::TestRaw);

    // CSSPropertyID::CSSPropertyTestRenderStyleStorageOneLevelReference
    inline const Style::Number<>& testRenderStyleStorageOneLevelReference() const;
    inline void setTestRenderStyleStorageOneLevelReference(Style::Number<>&&);

    // CSSPropertyID::CSSPropertyTestRenderStyleStorageOneLevelValue
    inline Style::Number<> testRenderStyleStorageOneLevelValue() const;
    inline void setTestRenderStyleStorageOneLevelValue(Style::Number<>);

    // CSSPropertyID::CSSPropertyTestRenderStyleStorageTwoLevelEnum
    inline Style::TestEnumeration testRenderStyleStorageTwoLevelEnum() const;
    inline void setTestRenderStyleStorageTwoLevelEnum(Style::TestEnumeration);

    // CSSPropertyID::CSSPropertyTestRenderStyleStorageTwoLevelRaw
    inline Style::TestRaw testRenderStyleStorageTwoLevelRaw() const;
    inline void setTestRenderStyleStorageTwoLevelRaw(Style::TestRaw);

    // CSSPropertyID::CSSPropertyTestRenderStyleStorageTwoLevelReference
    inline const Style::Number<>& testRenderStyleStorageTwoLevelReference() const;
    inline void setTestRenderStyleStorageTwoLevelReference(Style::Number<>&&);

    // CSSPropertyID::CSSPropertyTestRenderStyleStorageTwoLevelValue
    inline Style::Number<> testRenderStyleStorageTwoLevelValue() const;
    inline void setTestRenderStyleStorageTwoLevelValue(Style::Number<>);
};

} // namespace WebCore

